import type { Metadata } from 'next';
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-white shadow p-4 flex gap-4">
          <Link href="/" className="font-bold">
            Art Gallery Contest
          </Link>
          <Link href="/auth/register">Register</Link>
          <Link href="/auth/login">Login</Link>
          <Link href="/upload">Upload</Link>
          <Link href="/my-gallery">My Gallery</Link>
          <Link href="/gallery">Gallery</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
